### ISSUE TITLE
GraphQL Server not Config'd Properly on Fresh Install

### ISSUE THREAD

**Issue by brandon-hedrick** [air-hockey/match-history#1]
Steps to Repro:
- install project deps via `yarn` 
- start `docker`
- run `npm run server`
- navigate to [localhost:3000](http://localhost:3000/)

Output (in console): 
![image](https://user-images.githubusercontent.com/6598295/40879802-519fbc3c-666b-11e8-97ff-4f65d0d00faf.png)

Thoughts:
- Is there a config file that isn't in GH?
- Version mismatches?

@markbrouch

**Comment by markbrouch** [comment]
Should be fixed now. Run `yarn server` again after pulling latest.
